import uuid
from dataclasses import dataclass, field
from datetime import datetime, timezone
from decimal import Decimal
from typing import Optional

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.config import settings
from app.models.orm import Account, Position, PositionLot
from app.services.order_engine import get_last_price, get_latest_market_time

# The feed replays 2026-06-30 09:30 UTC onward (see data/simulation_price_data_*).
# CAGR is anchored to simulated elapsed time from this date, not real elapsed
# time since account.created_at -- accounts are seeded moments before use in
# this demo, so "real" elapsed time is ~0, which would make CAGR explode
# (annualizing a return over a few minutes is meaningless). Simulated elapsed
# time gives a stable, interpretable number that scales as the feed progresses
# through its ~61-day window, regardless of real wall-clock time.
SIMULATION_START = datetime(2026, 6, 30, tzinfo=timezone.utc)


@dataclass
class PositionSummary:
    ticker: str
    signed_qty: int
    avg_cost: Decimal
    current_price: Decimal
    market_value: Decimal
    unrealized_pnl: Decimal
    realized_pnl: Decimal
    sector: str


@dataclass
class PortfolioSummary:
    cash_balance: Decimal
    margin_used: Decimal
    positions: list[PositionSummary] = field(default_factory=list)
    market_value_total: Decimal = Decimal("0")
    net_worth: Decimal = Decimal("0")
    unrealized_pnl_total: Decimal = Decimal("0")
    realized_pnl_total: Decimal = Decimal("0")
    cagr: Optional[Decimal] = None


async def apply_fill_to_position(
    db: AsyncSession,
    *,
    account_id: uuid.UUID,
    ticker: str,
    order_side: str,
    fill_qty: int,
    fill_price: Decimal,
    is_backtest: bool = False,
    is_intraday: bool = False,
    fill_id: Optional[uuid.UUID] = None,
) -> Decimal:
    """Applies one fill to the account's position in `ticker` via FIFO lot
    consumption, and refreshes the cached Position aggregate (signed_qty,
    avg_cost, realized_pnl). Returns the realized P&L generated by this
    fill (0 if it only opened/extended a position with nothing closed).

    A BUY fill closes SHORT lots first (FIFO, oldest first), then
    opens/extends a LONG lot with any remainder. A SELL fill closes LONG
    lots first, then opens/extends a SHORT lot with any remainder.
    """
    closing_side = "SHORT" if order_side == "BUY" else "LONG"
    opening_side = "LONG" if order_side == "BUY" else "SHORT"

    remaining = fill_qty
    realized_pnl = Decimal("0")

    open_lots = (
        await db.scalars(
            select(PositionLot)
            .where(
                PositionLot.account_id == account_id,
                PositionLot.ticker == ticker,
                PositionLot.is_backtest == is_backtest,
                PositionLot.is_intraday == is_intraday,
                PositionLot.side == closing_side,
                PositionLot.qty_remaining > 0,
            )
            .order_by(PositionLot.opened_at.asc())
        )
    ).all()

    for lot in open_lots:
        if remaining <= 0:
            break
        consumed = min(lot.qty_remaining, remaining)
        if closing_side == "LONG":
            realized_pnl += (fill_price - lot.cost_price) * consumed
        else:
            realized_pnl += (lot.cost_price - fill_price) * consumed
        lot.qty_remaining -= consumed
        remaining -= consumed

    if remaining > 0:
        db.add(
            PositionLot(
                account_id=account_id,
                ticker=ticker,
                is_backtest=is_backtest,
                is_intraday=is_intraday,
                side=opening_side,
                qty_remaining=remaining,
                cost_price=fill_price,
                fill_id=fill_id,
            )
        )

    await _refresh_position_aggregate(
        db, account_id, ticker, is_backtest, is_intraday, realized_pnl_delta=realized_pnl
    )
    return realized_pnl


async def _refresh_position_aggregate(
    db: AsyncSession,
    account_id: uuid.UUID,
    ticker: str,
    is_backtest: bool,
    is_intraday: bool,
    *,
    realized_pnl_delta: Decimal,
) -> None:
    lots = (
        await db.scalars(
            select(PositionLot).where(
                PositionLot.account_id == account_id,
                PositionLot.ticker == ticker,
                PositionLot.is_backtest == is_backtest,
                PositionLot.is_intraday == is_intraday,
                PositionLot.qty_remaining > 0,
            )
        )
    ).all()

    long_qty = sum(lot.qty_remaining for lot in lots if lot.side == "LONG")
    short_qty = sum(lot.qty_remaining for lot in lots if lot.side == "SHORT")
    net_qty = long_qty - short_qty

    if net_qty > 0:
        avg_cost = sum(lot.qty_remaining * lot.cost_price for lot in lots if lot.side == "LONG") / long_qty
    elif net_qty < 0:
        avg_cost = sum(lot.qty_remaining * lot.cost_price for lot in lots if lot.side == "SHORT") / short_qty
    else:
        avg_cost = Decimal("0")

    position = await db.scalar(
        select(Position).where(
            Position.account_id == account_id,
            Position.ticker == ticker,
            Position.is_backtest == is_backtest,
            Position.is_intraday == is_intraday,
        )
    )
    if position is None:
        position = Position(account_id=account_id, ticker=ticker, is_backtest=is_backtest, is_intraday=is_intraday)
        db.add(position)
        await db.flush()

    position.signed_qty = net_qty
    position.avg_cost = avg_cost
    position.realized_pnl = (position.realized_pnl or Decimal("0")) + realized_pnl_delta


def _compute_cagr(starting_capital: Decimal, net_worth: Decimal, current_market_time: Optional[datetime]) -> Optional[Decimal]:
    if starting_capital <= 0 or current_market_time is None:
        return None
    days_elapsed = (current_market_time - SIMULATION_START).days
    if days_elapsed <= 0:
        return None
    ratio = float(net_worth / starting_capital)
    if ratio <= 0:
        return None  # negative net worth -- CAGR (a fractional power) is undefined
    years = days_elapsed / 365.0
    cagr = ratio ** (1 / years) - 1
    return Decimal(str(round(cagr, 6)))


async def get_portfolio(db: AsyncSession, account: Account, *, is_backtest: bool = False) -> PortfolioSummary:
    positions = (
        await db.scalars(
            select(Position).where(
                Position.account_id == account.id,
                Position.is_backtest == is_backtest,
                Position.signed_qty != 0,
            )
        )
    ).all()

    summaries: list[PositionSummary] = []
    market_value_total = Decimal("0")
    unrealized_total = Decimal("0")
    realized_total = Decimal("0")

    for p in positions:
        current_price = await get_last_price(db, p.ticker) or p.avg_cost
        market_value = p.signed_qty * current_price
        unrealized = (current_price - p.avg_cost) * p.signed_qty
        summaries.append(
            PositionSummary(
                ticker=p.ticker,
                signed_qty=p.signed_qty,
                avg_cost=p.avg_cost,
                current_price=current_price,
                market_value=market_value,
                unrealized_pnl=unrealized,
                realized_pnl=p.realized_pnl,
                sector=settings.SECTOR_BY_TICKER.get(p.ticker, "Other"),
            )
        )
        market_value_total += market_value
        unrealized_total += unrealized
        realized_total += p.realized_pnl

    net_worth = account.cash_balance + market_value_total
    current_market_time = await get_latest_market_time(db)
    cagr = _compute_cagr(account.starting_capital, net_worth, current_market_time)

    return PortfolioSummary(
        cash_balance=account.cash_balance,
        margin_used=account.margin_used,
        positions=summaries,
        market_value_total=market_value_total,
        net_worth=net_worth,
        unrealized_pnl_total=unrealized_total,
        realized_pnl_total=realized_total,
        cagr=cagr,
    )


async def get_sector_exposure(db: AsyncSession, account: Account) -> list[dict]:
    portfolio = await get_portfolio(db, account)
    totals: dict[str, Decimal] = {}
    for p in portfolio.positions:
        totals[p.sector] = totals.get(p.sector, Decimal("0")) + p.market_value

    return [
        {
            "sector": sector,
            "market_value": value,
            "pct_of_net_worth": (value / portfolio.net_worth * 100) if portfolio.net_worth else Decimal("0"),
        }
        for sector, value in totals.items()
    ]
