"""initial_schema_15_tables

Revision ID: 6d4d59aea235
Revises:
Create Date: 2026-08-02 12:17:40.930406

Generated via `alembic revision --autogenerate` against a live, empty
Postgres instance (the first time Docker was available for this project).
Supersedes two hand-authored migrations that had to be collapsed: the
original e06279dbbf6e used `Base.metadata.create_all()` inside upgrade(),
which reads the ORM's *live* state at migration-run time rather than a
frozen snapshot -- so a later change to orm.py (adding
KYCSubmission.declared_full_name) silently changed what that "initial"
migration created, and the follow-up migration adding that same column
then failed with DuplicateColumnError on a fresh database. Static,
autogenerated op.create_table()/op.add_column() calls like this don't
have that problem since they don't re-read the model at run time.

Two things autogenerate doesn't detect (outside SQLAlchemy's declarative
metadata) are added by hand below: the pgcrypto extension (needed for the
gen_random_uuid() server defaults) and the 7 ticker partitions of
price_history_minute (MASTER_BUILD_PLAN Part 3's PARTITION BY LIST design).
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6d4d59aea235'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# One partition per ticker, per MASTER_BUILD_PLAN Part 3's
# `PARTITION BY LIST (ticker)` design for price_history_minute.
TICKER_PARTITIONS = ["AAPL", "GOOG", "IBM", "MSFT", "TSLA", "UL", "WMT"]


def upgrade() -> None:
    # gen_random_uuid() (server_default for every UUID primary key) is
    # provided by pgcrypto.
    op.execute('CREATE EXTENSION IF NOT EXISTS "pgcrypto"')

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('kyc_status', sa.String(length=20), server_default='NOT_STARTED', nullable=False),
    sa.Column('starting_capital', sa.Numeric(precision=15, scale=2), server_default='1000000.00', nullable=False),
    sa.Column('cash_balance', sa.Numeric(precision=15, scale=2), server_default='1000000.00', nullable=False),
    sa.Column('margin_multiplier', sa.Numeric(precision=3, scale=1), server_default='1.0', nullable=False),
    sa.Column('margin_used', sa.Numeric(precision=15, scale=2), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.CheckConstraint("kyc_status IN ('NOT_STARTED','PENDING_REVIEW','APPROVED','REJECTED')", name='ck_accounts_kyc_status'),
    sa.CheckConstraint("role IN ('trader', 'admin')", name='ck_accounts_role'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('news_sentiment_daily',
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('avg_sentiment', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('headline_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('ticker', 'date')
    )
    op.create_table('price_history_daily',
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('open', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('high', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('low', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('close', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('adj_close', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=False),
    sa.Column('dividend_amount', sa.Numeric(precision=10, scale=4), server_default='0', nullable=False),
    sa.Column('split_coefficient', sa.Numeric(precision=6, scale=4), server_default='1.0', nullable=False),
    sa.PrimaryKeyConstraint('ticker', 'date')
    )
    op.create_table('price_history_minute',
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('high', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('low', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('close', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('ticker', 'timestamp'),
    postgresql_partition_by='LIST (ticker)'
    )
    op.create_table('cash_ledger',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('reason', sa.String(length=50), nullable=False),
    sa.Column('is_backtest', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kyc_submissions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('id_type', sa.String(length=30), nullable=False),
    sa.Column('document_path', sa.Text(), nullable=False),
    sa.Column('declared_full_name', sa.Text(), nullable=False),
    sa.Column('extracted_full_name', sa.Text(), nullable=True),
    sa.Column('extracted_dob', sa.Date(), nullable=True),
    sa.Column('extracted_id_number', sa.Text(), nullable=True),
    sa.Column('extracted_expiry_date', sa.Date(), nullable=True),
    sa.Column('extracted_issuing_country', sa.String(length=3), nullable=True),
    sa.Column('extraction_confidence', sa.String(length=10), nullable=True),
    sa.Column('auto_check_passed', sa.Boolean(), nullable=True),
    sa.Column('auto_check_notes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='PENDING_REVIEW', nullable=False),
    sa.Column('reviewed_by_admin_id', sa.UUID(), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_admin_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_kyc_account_status', 'kyc_submissions', ['account_id', 'status'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('side', sa.String(length=4), nullable=False),
    sa.Column('type', sa.String(length=6), nullable=False),
    sa.Column('product_type', sa.String(length=3), server_default='CNC', nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('remaining_qty', sa.Integer(), nullable=False),
    sa.Column('limit_price', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('stop_trigger_price', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('stop_limit_price', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='NEW', nullable=False),
    sa.Column('is_backtest', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.CheckConstraint("product_type IN ('CNC', 'MIS')", name='ck_orders_product_type'),
    sa.CheckConstraint("side IN ('BUY', 'SELL')", name='ck_orders_side'),
    sa.CheckConstraint("status IN ('NEW','VALIDATED','ROUTED','FILLED','REJECTED','CANCELLED')", name='ck_orders_status'),
    sa.CheckConstraint('"type" IN (\'MARKET\', \'LIMIT\', \'SL\', \'SL-M\')', name='ck_orders_type'),
    sa.CheckConstraint('qty > 0', name='ck_orders_qty_positive'),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_orders_account_status', 'orders', ['account_id', 'status'], unique=False)
    op.create_index('idx_orders_backtest', 'orders', ['is_backtest'], unique=False)
    op.create_index('idx_orders_ticker_matching', 'orders', ['ticker', 'side', 'type', 'status'], unique=False, postgresql_where=sa.text("status IN ('VALIDATED', 'ROUTED')"))
    op.create_table('positions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('signed_qty', sa.Integer(), server_default='0', nullable=False),
    sa.Column('avg_cost', sa.Numeric(precision=10, scale=4), server_default='0', nullable=False),
    sa.Column('realized_pnl', sa.Numeric(precision=15, scale=2), server_default='0', nullable=False),
    sa.Column('is_backtest', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_intraday', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'ticker', 'is_backtest', 'is_intraday', name='uq_positions_account_ticker')
    )
    op.create_index('idx_positions_account', 'positions', ['account_id'], unique=False)
    op.create_table('strategies',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('entry_rule', sa.Text(), nullable=False),
    sa.Column('exit_rule', sa.Text(), nullable=False),
    sa.Column('position_size', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trader_behavioral_history',
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('recent_trades', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'"), nullable=False),
    sa.Column('today_order_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('today_pnl', sa.Numeric(precision=15, scale=2), server_default='0', nullable=False),
    sa.Column('session_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_loss_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_loss_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('streak_type', sa.String(length=4), nullable=True),
    sa.Column('streak_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('avg_order_size', sa.Numeric(precision=15, scale=2), server_default='0', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('account_id')
    )
    op.create_table('backtest_runs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('strategy_id', sa.UUID(), nullable=False),
    sa.Column('total_return', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('max_drawdown', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('win_rate', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('benchmark_return', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('run_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('behavioral_scores',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=True),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('brs', sa.Integer(), nullable=False),
    sa.Column('biases_detected', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'"), nullable=False),
    sa.Column('intervention_shown', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('intervention_text', sa.Text(), nullable=True),
    sa.Column('trader_proceeded', sa.Boolean(), nullable=True),
    sa.Column('trader_acknowledged', sa.Boolean(), nullable=True),
    sa.Column('calculated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.CheckConstraint('brs BETWEEN 0 AND 100', name='ck_behavioral_scores_brs_range'),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_behavioral_account', 'behavioral_scores', ['account_id', 'calculated_at'], unique=False)
    op.create_index('idx_behavioral_high_risk', 'behavioral_scores', ['brs'], unique=False, postgresql_where=sa.text('brs > 50'))
    op.create_table('fills',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('fill_price', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('fill_qty', sa.Integer(), nullable=False),
    sa.Column('fees', sa.Numeric(precision=10, scale=4), server_default='1.00', nullable=False),
    sa.Column('is_backtest', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('reason', sa.String(length=50), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_fills_order', 'fills', ['order_id'], unique=False)
    op.create_table('order_events',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('from_state', sa.String(length=20), nullable=True),
    sa.Column('to_state', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('is_backtest', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_order_events_order', 'order_events', ['order_id', 'timestamp'], unique=False)
    op.create_table('order_matches',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('matched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('match_type', sa.String(length=20), nullable=False),
    sa.Column('fill_price', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('fill_qty', sa.Integer(), nullable=False),
    sa.Column('counterparty_account_id', sa.UUID(), nullable=True),
    sa.Column('nse_match_algorithm', sa.String(length=50), server_default='NSE_FIFO_PriceTime_v1', nullable=True),
    sa.Column('matching_log', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['counterparty_account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    for ticker in TICKER_PARTITIONS:
        op.execute(
            f"CREATE TABLE price_history_minute_{ticker.lower()} "
            f"PARTITION OF price_history_minute FOR VALUES IN ('{ticker}')"
        )


def downgrade() -> None:
    for ticker in TICKER_PARTITIONS:
        op.execute(f"DROP TABLE IF EXISTS price_history_minute_{ticker.lower()}")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_matches')
    op.drop_index('idx_order_events_order', table_name='order_events')
    op.drop_table('order_events')
    op.drop_index('idx_fills_order', table_name='fills')
    op.drop_table('fills')
    op.drop_index('idx_behavioral_high_risk', table_name='behavioral_scores', postgresql_where=sa.text('brs > 50'))
    op.drop_index('idx_behavioral_account', table_name='behavioral_scores')
    op.drop_table('behavioral_scores')
    op.drop_table('backtest_runs')
    op.drop_table('trader_behavioral_history')
    op.drop_table('strategies')
    op.drop_index('idx_positions_account', table_name='positions')
    op.drop_table('positions')
    op.drop_index('idx_orders_ticker_matching', table_name='orders', postgresql_where=sa.text("status IN ('VALIDATED', 'ROUTED')"))
    op.drop_index('idx_orders_backtest', table_name='orders')
    op.drop_index('idx_orders_account_status', table_name='orders')
    op.drop_table('orders')
    op.drop_index('idx_kyc_account_status', table_name='kyc_submissions')
    op.drop_table('kyc_submissions')
    op.drop_table('cash_ledger')
    op.drop_table('price_history_minute')
    op.drop_table('price_history_daily')
    op.drop_table('news_sentiment_daily')
    op.drop_table('accounts')
    # ### end Alembic commands ###
